# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('appmsgid', models.CharField(default=None, help_text='一条推送消息可以有多篇文章', max_length=20, verbose_name='推送消息ID')),
                ('seq', models.IntegerField(default=0, verbose_name='推送的第几条')),
                ('article_id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='文章唯一ID')),
                ('comment_id', models.CharField(default=None, max_length=20, verbose_name='文章评论ID')),
                ('comment_num', models.IntegerField(default=0, verbose_name='评论数')),
                ('reprint_num', models.IntegerField(default=0, help_text='公众号转载，非转发数', verbose_name='转载数')),
                ('like_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('read_num', models.IntegerField(default=0, verbose_name='阅读量')),
                ('share_num', models.IntegerField(default=0, verbose_name='分享量')),
                ('title', models.CharField(default=None, max_length=511, verbose_name='标题')),
                ('cover', models.CharField(max_length=1023, verbose_name='头图')),
                ('content_url', models.CharField(max_length=1023, verbose_name='文章正文链接')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('send_time', models.BigIntegerField(default=0, verbose_name='推送时间')),
                ('content', models.TextField(default=None, verbose_name='文章正文')),
                ('content_pure', models.TextField(default=None, verbose_name='纯文字文章正文')),
                ('cdn_cover', models.CharField(default=None, max_length=1023, verbose_name='转存到七牛云的头图')),
                ('cdn_content', models.TextField(default=None, verbose_name='转存到七牛云的文章正文')),
                ('status', models.IntegerField(choices=[(0, '创建条目'), (1, '抓取内容'), (2, '转存七牛')], default=0, verbose_name='文章抓取状态')),
            ],
        ),
    ]
