# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_auto_20170612_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(db_index=True, default=None, max_length=30, unique=True, verbose_name='评论正文唯一ID')),
                ('nick_name', models.CharField(default=None, max_length=100, verbose_name='用户昵称')),
                ('post_time', models.BigIntegerField(default=0, verbose_name='留言时间')),
                ('comment_id', models.CharField(db_index=True, default=None, max_length=20, verbose_name='文章评论ID')),
                ('content', models.CharField(default=None, max_length=1023, verbose_name='评论正文')),
                ('icon', models.CharField(default=None, max_length=1200, verbose_name='评论头像')),
                ('article_comment_id', models.IntegerField(default=0, help_text='第几个评论的', verbose_name='文章评论序号')),
                ('is_elected', models.IntegerField(default=0, verbose_name='是否被选择作为精选留言')),
                ('is_top', models.IntegerField(default=0, verbose_name='是否为置顶留言')),
                ('my_id', models.IntegerField(default=0, verbose_name='我还真不知道这个字段有啥卵用')),
                ('status', models.IntegerField(default=0, verbose_name='我还真不知道这个字段有啥卵用')),
                ('del_flag', models.IntegerField(default=0, verbose_name='应该是是否删除')),
            ],
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_reply_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='评论回复唯一ID')),
                ('content_id', models.CharField(default=None, max_length=30, verbose_name='Comment表评论正文唯一ID')),
                ('reply_id', models.IntegerField(default=0, verbose_name='回复ID')),
                ('content', models.CharField(default=None, max_length=1023, verbose_name='回复正文')),
                ('create_time', models.BigIntegerField(default=0, verbose_name='回复时间')),
                ('reply_like_num', models.IntegerField(default=0, verbose_name='回复的点赞数')),
                ('to_uin', models.CharField(default=None, max_length=20, verbose_name='我还真不知道这个字段有啥卵用')),
                ('uin', models.CharField(default=None, max_length=20, verbose_name='我还真不知道这个字段有啥卵用')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.IntegerField(choices=[(0, '创建条目'), (1, '抓取内容'), (2, '转存七牛'), (3, '抓取评论')], default=0, verbose_name='文章抓取状态'),
        ),
    ]
