# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0003_auto_20170614_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAnalyse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='创建时间')),
                ('comment_num', models.IntegerField(default=0, verbose_name='评论数')),
                ('reprint_num', models.IntegerField(default=0, help_text='公众号转载，非转发数', verbose_name='转载数')),
                ('like_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('read_num', models.IntegerField(default=0, verbose_name='阅读量')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Article.Article', verbose_name='关联文章')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleAnalyseShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='创建时间')),
                ('share_num', models.IntegerField(default=0, verbose_name='分享量')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Article.Article', verbose_name='关联文章')),
            ],
        ),
    ]
